### ISSUE TITLE
I wanted to say thank you for the Satchel Scanner addon for 10.0

### ISSUE THREAD

**Issue by ghost** [theriou/Satchel-Scanner#1]
A large part of my game enjoyment comes from doing random dungeons for the Satchel, and your addon is the only one out of 7 or so that I tried that worked. Thank you!!!

I wasn't sure how to message you directly. I hope this is okay. Bye! Thank you!

**Comment by theriou** [comment]
Thanks, I've been trying to keep it going for Retail :)

**Comment by theriou** [comment]
Thanks, I've been trying to keep it going for Retail :)

Have been looking on maybe getting it onto a searchable UI place too, I know WoWUp has a Wago and Curseforge version, maybe picking one or both

**Comment by CyberRubyFox** [comment]
I also wanted to thank you! I searched around for something to do exactly this and found prior versions. When I saw they were out of date I figured this would be too. To my surprise...! :)
